### ISSUE TITLE
Open Mailbox is not working keyword 

### ISSUE THREAD

**Issue by mecanda12** [rickypc/robotframework-imaplibrary#21]
. I keep get an error  “ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it” .

My code is given below 
Open Mailbox   host=outlook.office365.com  user=t********@outlook.com  password=*******  port=993

**Comment by mecanda12** [comment]
New version of robotframework-imaplibrary2 0.3.2 is broken. It is not working on Python 3.7.4. 
I get an error No keyword with name 'Open Mailbox' found, when I run code. 
--

**Comment by lasselindqvist** [comment]
So the robotframework-imaplibrary2 0.3.2 is actually deployed from my fork.
You can see the new commits here https://github.com/lasselindqvist/robotframework-imaplibrary/commits/master
It actually only contains the naming change (adding the number 2) and the email encoding handling https://github.com/lasselindqvist/robotframework-imaplibrary/commit/fc462da9488691d04883edefb78d103a6bd072a4 change.
Sorry for the confusion about the naming.
Any connection issues should not be because of these changes, so your problem is probably something else.
